### ISSUE TITLE
Buffer telegram logging when logs cannot be sent

### ISSUE THREAD

**Issue by bertye** [bertye/MemeHub-Logger#1]
```
Failed to send log to telegram TelegramError: 429: Too Many Requests: retry after 43
    at /home/memehub/MemeHub-Logger/node_modules/telegraf/core/network/client.js:281:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.log (/home/memehub/MemeHub-Logger/src/targets/telegram.js:40:21)
    at async sendLog (/home/memehub/MemeHub-Logger/src/save-log.js:87:17)
    at async Subscriber.handleLog [as handle] (/home/memehub/MemeHub-Logger/src/save-log.js:45:13)
    at async Subscriber._onMessage (/home/memehub/MemeHub-Logger/node_modules/redis-request-broker/lib/subscriber.js:124:13) {
  code: 429,
  response: {
    ok: false,
    error_code: 429,
    description: 'Too Many Requests: retry after 43',
    parameters: { retry_after: 43 }
  },
  description: 'Too Many Requests: retry after 43',
  parameters: { retry_after: 43 },

```

**Comment by bertye** [comment]
maybe also yield logs if that error happens
